# Edit this file to set the Messenger's module settings programmatically instead of using the GUI
# This is regular YAML syntax. See http://docs.ansible.com/ansible/YAMLSyntax.html
# You can override these settings with ENV variables. They are commented below.


applicationID: ''
accessToken: ''
appSecret: ''
verifyToken: 'VERIFY_TOKEN'
hostname: ''

displayGetStarted: true
greetingMessage: "Merhaba"

# https://developers.facebook.com/docs/messenger-platform/messenger-profile/persistent-menu
# persistentMenuItems: []

# targetAudience: openToAll
# targetAudienceOpenToSome: ""
# targetAudienceCloseToSome: ""

# trustedDomains: []
# autoRespondGetStarted: true

# paymentTesters: []

# chatExtensionHomeUrl: ""
# chatExtensionInTest: true
# chatExtensionShowShareButton: false

enabled: true